server:
  port: 9300

spring:
  application:
    name: mymall-zuul
  main:
    allow-bean-definition-overriding: true

zuul:
  routes:
    mymall-auth-server:
      path: /auu/**
      serviceId: mymall-auth-server #微服务名称，网关会从eureka中获取该服务名称下的服务实例的地址
      strip-prefix: true #true：代理转发时去掉前缀，false:代理转发时不去掉前缀
      sensitiveHeaders:  #默认zuul会屏蔽cookie，cookie不会传到下游服务，这里设置为空则取消默认的黑名单，如果设置了具体的头信息则不会传到下游服务
      #   ignoredHeaders: 默认为空表示不过虑任何头
    mymall-order:  #路由名称，名称任意，保持所有路由名称唯一
      path: /ord/**
      serviceId: mymall-order #指定服务id，从Eureka中找到服务的ip和端口
      strip-prefix: true
      sensitiveHeaders:
    mymall-user-center:  #路由名称，名称任意，保持所有路由名称唯一
      path: /user/**
      serviceId: mymall-user-center #指定服务id，从Eureka中找到服务的ip和端口
      strip-prefix: true
      sensitiveHeaders:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}


security:
  oauth2:
    client:
      client-id: c2
      client-secret: 123
    resource:
      jwt:
        key-uri: http://localhost:9001/oauth/token_key

ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 50000  #请求连接的超时时间
  ReadTimeout: 60000 #请求处理的超时时间

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 50000 #断路器超时时间，默认1000ms

feign:
  hystrix:
    enabled: true
  #请求和响应GZIP压缩支持
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types:
        - text/xml
        - application/xml
        - application/json
    response:
      enabled: true


management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true

logging:
  level:
    com.github: debug



