server:
  port: 9001

spring:
  application:
    name: mymall-auth-server
  #数据源配置
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/mymall_security?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #druid的属性
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    defaultAutoCommit: false
  main:
    allow-bean-definition-overriding: true

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  typeAliasesPackage: com.github.model
  #  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      #field-strategy: not_empty
      #驼峰下划线转换
      #      column-underline: false
      #数据库大写下划线转换
      #      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
    refresh: true
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

security:
  oauth2:
    client:
      client-id: auth
      client-secret: 123

logging:
  level:
    com.github: debug



